sonar.projectKey=dimdasci_bproxy
sonar.organization=dimdasci

sonar.sources=cli/src,service/src,extension/src,shared/src
sonar.tests=cli/src/__tests__,service/src/__tests__,extension/src

sonar.test.inclusions=**/__tests__/**,**/test/**,**/*.test.ts

# Exclude test files and fixtures from duplication detection
sonar.cpd.exclusions=**/__tests__/**,**/test/**,**/*.test.ts
